### ISSUE TITLE
Going back to index page after polling.

### ISSUE THREAD

**Issue by jai-dewani** [utkarsh-raj/polling-webapp#1]
There is no direct way for me to go back to the index page after having given my views on 'n' polls other than to click back button 'n' times.

**Comment by utkarsh-raj** [comment]
My apologies for the layout, but there is a Go Back URL at the end.

https://github.com/utkarsh-raj/polling-webapp/blob/master/views/index.ejs#L122

**Comment by jai-dewani** [comment]
You might wanna put it somewhere more visible.
